//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole2
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Role { get; set; }
    
        public virtual UserRole2 UserRole21 { get; set; }
        public virtual UserRole2 UserRole22 { get; set; }
    }
}
